### ISSUE TITLE
Sample.hx:2: characters 8-20 : Module SampleModule does not define type SampleModule

### ISSUE THREAD

**Issue by WolfieWerewolf** [ncannasse/webidl#11]
Hi Guys.. I'm trying to build the sample on Linux Mint (Ubuntu derivative).  I am using 4.0.0-rc.1 which I cloned and built from github and emscripten incoming as per the previous post.  Any assistance would be appreciated.
Kind Regards
/W

**Comment by zicklag** [comment]
Are you building it by running the `make js` in the `sample/` directory?

**Comment by WolfieWerewolf** [comment]
@zicklag Thanks for responding.. yes I've gone through each of the build steps in the Makefile excluding the one for windows and it fails when I attempt to execute make js or the command line it executes manually.

Thanks

**Comment by zicklag** [comment]
No problem. :slightly_smiling_face:  

So I just installed Haxe 4.0.0-rc1 and it works for me on Ubuntu 16.04. In the webidl repo try running `haxelib dev webidl .` and then running `make js` again.

**Comment by WolfieWerewolf** [comment]
@zicklag Magic!  I had previously pulled an older version into my haxelib folder and so that was being referenced.. Thank you!
